// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package base

import (
	"database/sql"
	"time"
)

type Certificate struct {
	ID                            int64          `json:"id"`
	SerialNumber                  string         `json:"serial_number"`
	CommonName                    string         `json:"common_name"`
	Type                          string         `json:"type"`
	KeyName                       string         `json:"key_name"`
	IssuerCertificateSerialNumber sql.NullString `json:"issuer_certificate_serial_number"`
	NotBefore                     time.Time      `json:"not_before"`
	NotAfter                      time.Time      `json:"not_after"`
	IsRevoked                     sql.NullInt64  `json:"is_revoked"`
	RevocationReason              sql.NullInt64  `json:"revocation_reason"`
	RevocationTime                sql.NullTime   `json:"revocation_time"`
	CertificatePem                string         `json:"certificate_pem"`
	CreatedAt                     sql.NullTime   `json:"created_at"`
}

type Key struct {
	ID            int64        `json:"id"`
	Name          string       `json:"name"`
	Algorithm     string       `json:"algorithm"`
	PrivateKeyPem string       `json:"private_key_pem"`
	PublicKeyPem  string       `json:"public_key_pem"`
	CreatedAt     sql.NullTime `json:"created_at"`
}
