// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package base

import (
	"context"
)

type Querier interface {
	CreateCertificate(ctx context.Context, arg CreateCertificateParams) (Certificate, error)
	CreateKeyPair(ctx context.Context, arg CreateKeyPairParams) (Key, error)
	GetCertByCN(ctx context.Context, commonName string) (Certificate, error)
	GetCertBySN(ctx context.Context, serialNumber string) (Certificate, error)
	GetKeyByName(ctx context.Context, name string) (Key, error)
	ListCertificates(ctx context.Context, arg ListCertificatesParams) ([]ListCertificatesRow, error)
	ListKeys(ctx context.Context, arg ListKeysParams) ([]string, error)
	TotalCerts(ctx context.Context) (int64, error)
	TotalKeys(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
