// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package base

import (
	"context"
	"database/sql"
	"time"
)

const createCRL = `-- name: CreateCRL :one
INSERT INTO crls (
    name,
    crl_number,
    issuer_serial_number,
    this_update,
    next_update,
    crl_pem
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
RETURNING id, name, crl_number, issuer_serial_number, this_update, next_update, crl_pem, created_at
`

type CreateCRLParams struct {
	Name               string    `json:"name"`
	CrlNumber          int64     `json:"crl_number"`
	IssuerSerialNumber string    `json:"issuer_serial_number"`
	ThisUpdate         time.Time `json:"this_update"`
	NextUpdate         time.Time `json:"next_update"`
	CrlPem             string    `json:"crl_pem"`
}

func (q *Queries) CreateCRL(ctx context.Context, arg CreateCRLParams) (Crl, error) {
	row := q.db.QueryRowContext(ctx, createCRL,
		arg.Name,
		arg.CrlNumber,
		arg.IssuerSerialNumber,
		arg.ThisUpdate,
		arg.NextUpdate,
		arg.CrlPem,
	)
	var i Crl
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CrlNumber,
		&i.IssuerSerialNumber,
		&i.ThisUpdate,
		&i.NextUpdate,
		&i.CrlPem,
		&i.CreatedAt,
	)
	return i, err
}

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO certificates (
    serial_number,
    common_name,
    type,
    key_name,
    issuer_serial_number,
    skid,
    akid,
    not_before,
    not_after,
    certificate_pem
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10
)
RETURNING id, serial_number, common_name, type, key_name, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, created_at
`

type CreateCertificateParams struct {
	SerialNumber       string         `json:"serial_number"`
	CommonName         string         `json:"common_name"`
	Type               string         `json:"type"`
	KeyName            string         `json:"key_name"`
	IssuerSerialNumber sql.NullString `json:"issuer_serial_number"`
	Skid               string         `json:"skid"`
	Akid               string         `json:"akid"`
	NotBefore          time.Time      `json:"not_before"`
	NotAfter           time.Time      `json:"not_after"`
	CertificatePem     string         `json:"certificate_pem"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, createCertificate,
		arg.SerialNumber,
		arg.CommonName,
		arg.Type,
		arg.KeyName,
		arg.IssuerSerialNumber,
		arg.Skid,
		arg.Akid,
		arg.NotBefore,
		arg.NotAfter,
		arg.CertificatePem,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyName,
		&i.IssuerSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.Skid,
		&i.Akid,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.CreatedAt,
	)
	return i, err
}

const createKeyPair = `-- name: CreateKeyPair :one
INSERT INTO keys (
    name,
    algorithm,
    private_key_pem,
    public_key_pem
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
RETURNING id, name, algorithm, private_key_pem, public_key_pem, created_at
`

type CreateKeyPairParams struct {
	Name          string `json:"name"`
	Algorithm     string `json:"algorithm"`
	PrivateKeyPem string `json:"private_key_pem"`
	PublicKeyPem  string `json:"public_key_pem"`
}

func (q *Queries) CreateKeyPair(ctx context.Context, arg CreateKeyPairParams) (Key, error) {
	row := q.db.QueryRowContext(ctx, createKeyPair,
		arg.Name,
		arg.Algorithm,
		arg.PrivateKeyPem,
		arg.PublicKeyPem,
	)
	var i Key
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Algorithm,
		&i.PrivateKeyPem,
		&i.PublicKeyPem,
		&i.CreatedAt,
	)
	return i, err
}

const getAllCRL = `-- name: GetAllCRL :many
SELECT id, name, crl_number, issuer_serial_number, this_update, next_update, crl_pem, created_at FROM crls WHERE issuer_serial_number = ?1
`

func (q *Queries) GetAllCRL(ctx context.Context, issuerSerialNumber string) ([]Crl, error) {
	rows, err := q.db.QueryContext(ctx, getAllCRL, issuerSerialNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Crl
	for rows.Next() {
		var i Crl
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CrlNumber,
			&i.IssuerSerialNumber,
			&i.ThisUpdate,
			&i.NextUpdate,
			&i.CrlPem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCRLByName = `-- name: GetCRLByName :one
SELECT id, name, crl_number, issuer_serial_number, this_update, next_update, crl_pem, created_at FROM crls WHERE name = ?1
`

func (q *Queries) GetCRLByName(ctx context.Context, name string) (Crl, error) {
	row := q.db.QueryRowContext(ctx, getCRLByName, name)
	var i Crl
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CrlNumber,
		&i.IssuerSerialNumber,
		&i.ThisUpdate,
		&i.NextUpdate,
		&i.CrlPem,
		&i.CreatedAt,
	)
	return i, err
}

const getCertificateByCN = `-- name: GetCertificateByCN :one
SELECT id, serial_number, common_name, type, key_name, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, created_at FROM certificates WHERE common_name = ?1
`

func (q *Queries) GetCertificateByCN(ctx context.Context, commonName string) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertificateByCN, commonName)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyName,
		&i.IssuerSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.Skid,
		&i.Akid,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.CreatedAt,
	)
	return i, err
}

const getCertificateBySKID = `-- name: GetCertificateBySKID :one
SELECT id, serial_number, common_name, type, key_name, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, created_at FROM certificates WHERE skid = ?1
`

func (q *Queries) GetCertificateBySKID(ctx context.Context, skid string) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertificateBySKID, skid)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyName,
		&i.IssuerSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.Skid,
		&i.Akid,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.CreatedAt,
	)
	return i, err
}

const getCertificateBySN = `-- name: GetCertificateBySN :one
SELECT id, serial_number, common_name, type, key_name, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, created_at FROM certificates WHERE serial_number = ?1
`

func (q *Queries) GetCertificateBySN(ctx context.Context, serialNumber string) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertificateBySN, serialNumber)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyName,
		&i.IssuerSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.Skid,
		&i.Akid,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.CreatedAt,
	)
	return i, err
}

const getKeyByName = `-- name: GetKeyByName :one
SELECT id, name, algorithm, private_key_pem, public_key_pem, created_at FROM keys WHERE name = ?1
`

func (q *Queries) GetKeyByName(ctx context.Context, name string) (Key, error) {
	row := q.db.QueryRowContext(ctx, getKeyByName, name)
	var i Key
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Algorithm,
		&i.PrivateKeyPem,
		&i.PublicKeyPem,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestCRLNumber = `-- name: GetLatestCRLNumber :one
SELECT crl_number FROM crls WHERE issuer_serial_number = ?1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestCRLNumber(ctx context.Context, issuerSerialNumber string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLatestCRLNumber, issuerSerialNumber)
	var crl_number int64
	err := row.Scan(&crl_number)
	return crl_number, err
}

const getRevokedCertificates = `-- name: GetRevokedCertificates :many
SELECT id, serial_number, common_name, type, key_name, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, created_at FROM certificates
WHERE
    issuer_serial_number = ?1
AND is_revoked = 1
`

func (q *Queries) GetRevokedCertificates(ctx context.Context, issuerSerialNumber sql.NullString) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, getRevokedCertificates, issuerSerialNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.CommonName,
			&i.Type,
			&i.KeyName,
			&i.IssuerSerialNumber,
			&i.NotBefore,
			&i.NotAfter,
			&i.Skid,
			&i.Akid,
			&i.IsRevoked,
			&i.RevocationReason,
			&i.RevocationTime,
			&i.CertificatePem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificates = `-- name: ListCertificates :many
SELECT serial_number, common_name, type, not_after, is_revoked
FROM certificates
LIMIT ?2
OFFSET ?1
`

type ListCertificatesParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type ListCertificatesRow struct {
	SerialNumber string        `json:"serial_number"`
	CommonName   string        `json:"common_name"`
	Type         string        `json:"type"`
	NotAfter     time.Time     `json:"not_after"`
	IsRevoked    sql.NullInt64 `json:"is_revoked"`
}

func (q *Queries) ListCertificates(ctx context.Context, arg ListCertificatesParams) ([]ListCertificatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCertificates, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCertificatesRow
	for rows.Next() {
		var i ListCertificatesRow
		if err := rows.Scan(
			&i.SerialNumber,
			&i.CommonName,
			&i.Type,
			&i.NotAfter,
			&i.IsRevoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeys = `-- name: ListKeys :many
SELECT name, algorithm, created_at
FROM keys
LIMIT ?2
OFFSET ?1
`

type ListKeysParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type ListKeysRow struct {
	Name      string       `json:"name"`
	Algorithm string       `json:"algorithm"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) ListKeys(ctx context.Context, arg ListKeysParams) ([]ListKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listKeys, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKeysRow
	for rows.Next() {
		var i ListKeysRow
		if err := rows.Scan(&i.Name, &i.Algorithm, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCertificate = `-- name: RevokeCertificate :one
UPDATE certificates
SET
    is_revoked = COALESCE(?1, is_revoked),
    revocation_reason = COALESCE(?2, revocation_reason),
    revocation_time = COALESCE(?3, revocation_time)
WHERE serial_number = ?4
RETURNING id, serial_number, common_name, type, key_name, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, created_at
`

type RevokeCertificateParams struct {
	IsRevoked        sql.NullInt64 `json:"is_revoked"`
	RevocationReason sql.NullInt64 `json:"revocation_reason"`
	RevocationTime   sql.NullTime  `json:"revocation_time"`
	SerialNumber     string        `json:"serial_number"`
}

func (q *Queries) RevokeCertificate(ctx context.Context, arg RevokeCertificateParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, revokeCertificate,
		arg.IsRevoked,
		arg.RevocationReason,
		arg.RevocationTime,
		arg.SerialNumber,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyName,
		&i.IssuerSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.Skid,
		&i.Akid,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.CreatedAt,
	)
	return i, err
}

const totalCertificates = `-- name: TotalCertificates :one
SELECT COUNT(*) AS total_count FROM certificates
`

func (q *Queries) TotalCertificates(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalCertificates)
	var total_count int64
	err := row.Scan(&total_count)
	return total_count, err
}

const totalKeys = `-- name: TotalKeys :one
SELECT COUNT(*) AS total_keys FROM keys
`

func (q *Queries) TotalKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalKeys)
	var total_keys int64
	err := row.Scan(&total_keys)
	return total_keys, err
}

const updateCertificate = `-- name: UpdateCertificate :one
UPDATE certificates
SET
  common_name = COALESCE(?1, common_name),
  type = COALESCE(?2, type),
  key_name = COALESCE(?3, key_name),
  issuer_serial_number = COALESCE(?4, issuer_serial_number),
  skid = COALESCE(?5, skid),
  akid = COALESCE(?6, akid),
  not_before = COALESCE(?7, not_before),
  not_after = COALESCE(?8, not_after),
  certificate_pem = COALESCE(?9, certificate_pem)
WHERE serial_number = ?10
RETURNING id, serial_number, common_name, type, key_name, issuer_serial_number, not_before, not_after, skid, akid, is_revoked, revocation_reason, revocation_time, certificate_pem, created_at
`

type UpdateCertificateParams struct {
	CommonName         sql.NullString `json:"common_name"`
	Type               sql.NullString `json:"type"`
	KeyName            sql.NullString `json:"key_name"`
	IssuerSerialNumber sql.NullString `json:"issuer_serial_number"`
	Skid               sql.NullString `json:"skid"`
	Akid               sql.NullString `json:"akid"`
	NotBefore          sql.NullTime   `json:"not_before"`
	NotAfter           sql.NullTime   `json:"not_after"`
	CertificatePem     sql.NullString `json:"certificate_pem"`
	SerialNumber       string         `json:"serial_number"`
}

func (q *Queries) UpdateCertificate(ctx context.Context, arg UpdateCertificateParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, updateCertificate,
		arg.CommonName,
		arg.Type,
		arg.KeyName,
		arg.IssuerSerialNumber,
		arg.Skid,
		arg.Akid,
		arg.NotBefore,
		arg.NotAfter,
		arg.CertificatePem,
		arg.SerialNumber,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyName,
		&i.IssuerSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.Skid,
		&i.Akid,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.CreatedAt,
	)
	return i, err
}
