// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package base

import (
	"context"
	"database/sql"
	"time"
)

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO certificates (
    serial_number,
    common_name,
    type,
    key_name,
    issuer_certificate_serial_number,
    not_before,
    not_after,
    certificate_pem
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, serial_number, common_name, type, key_name, issuer_certificate_serial_number, not_before, not_after, is_revoked, revocation_reason, revocation_time, certificate_pem, created_at
`

type CreateCertificateParams struct {
	SerialNumber                  string         `json:"serial_number"`
	CommonName                    string         `json:"common_name"`
	Type                          string         `json:"type"`
	KeyName                       string         `json:"key_name"`
	IssuerCertificateSerialNumber sql.NullString `json:"issuer_certificate_serial_number"`
	NotBefore                     time.Time      `json:"not_before"`
	NotAfter                      time.Time      `json:"not_after"`
	CertificatePem                string         `json:"certificate_pem"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, createCertificate,
		arg.SerialNumber,
		arg.CommonName,
		arg.Type,
		arg.KeyName,
		arg.IssuerCertificateSerialNumber,
		arg.NotBefore,
		arg.NotAfter,
		arg.CertificatePem,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyName,
		&i.IssuerCertificateSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.CreatedAt,
	)
	return i, err
}

const createKeyPair = `-- name: CreateKeyPair :one
INSERT INTO keys (
    name,
    algorithm,
    private_key_pem,
    public_key_pem
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, name, algorithm, private_key_pem, public_key_pem, created_at
`

type CreateKeyPairParams struct {
	Name          string `json:"name"`
	Algorithm     string `json:"algorithm"`
	PrivateKeyPem string `json:"private_key_pem"`
	PublicKeyPem  string `json:"public_key_pem"`
}

func (q *Queries) CreateKeyPair(ctx context.Context, arg CreateKeyPairParams) (Key, error) {
	row := q.db.QueryRowContext(ctx, createKeyPair,
		arg.Name,
		arg.Algorithm,
		arg.PrivateKeyPem,
		arg.PublicKeyPem,
	)
	var i Key
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Algorithm,
		&i.PrivateKeyPem,
		&i.PublicKeyPem,
		&i.CreatedAt,
	)
	return i, err
}

const getCertByCN = `-- name: GetCertByCN :one
SELECT id, serial_number, common_name, type, key_name, issuer_certificate_serial_number, not_before, not_after, is_revoked, revocation_reason, revocation_time, certificate_pem, created_at FROM certificates WHERE common_name = ?
`

func (q *Queries) GetCertByCN(ctx context.Context, commonName string) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertByCN, commonName)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyName,
		&i.IssuerCertificateSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.CreatedAt,
	)
	return i, err
}

const getCertBySN = `-- name: GetCertBySN :one
SELECT id, serial_number, common_name, type, key_name, issuer_certificate_serial_number, not_before, not_after, is_revoked, revocation_reason, revocation_time, certificate_pem, created_at FROM certificates WHERE serial_number = ?
`

func (q *Queries) GetCertBySN(ctx context.Context, serialNumber string) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertBySN, serialNumber)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.CommonName,
		&i.Type,
		&i.KeyName,
		&i.IssuerCertificateSerialNumber,
		&i.NotBefore,
		&i.NotAfter,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.RevocationTime,
		&i.CertificatePem,
		&i.CreatedAt,
	)
	return i, err
}

const getKeyByName = `-- name: GetKeyByName :one
SELECT id, name, algorithm, private_key_pem, public_key_pem, created_at FROM keys WHERE name = ?
`

func (q *Queries) GetKeyByName(ctx context.Context, name string) (Key, error) {
	row := q.db.QueryRowContext(ctx, getKeyByName, name)
	var i Key
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Algorithm,
		&i.PrivateKeyPem,
		&i.PublicKeyPem,
		&i.CreatedAt,
	)
	return i, err
}

const listCertificates = `-- name: ListCertificates :many
SELECT serial_number, common_name FROM certificates LIMIT ? OFFSET ?
`

type ListCertificatesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListCertificatesRow struct {
	SerialNumber string `json:"serial_number"`
	CommonName   string `json:"common_name"`
}

func (q *Queries) ListCertificates(ctx context.Context, arg ListCertificatesParams) ([]ListCertificatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCertificates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCertificatesRow
	for rows.Next() {
		var i ListCertificatesRow
		if err := rows.Scan(&i.SerialNumber, &i.CommonName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeys = `-- name: ListKeys :many
SELECT name FROM keys LIMIT ? OFFSET ?
`

type ListKeysParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListKeys(ctx context.Context, arg ListKeysParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listKeys, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalCerts = `-- name: TotalCerts :one
SELECT COUNT(*) AS total_count FROM certificates
`

func (q *Queries) TotalCerts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalCerts)
	var total_count int64
	err := row.Scan(&total_count)
	return total_count, err
}

const totalKeys = `-- name: TotalKeys :one
SELECT COUNT(*) AS total_keys FROM keys
`

func (q *Queries) TotalKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalKeys)
	var total_keys int64
	err := row.Scan(&total_keys)
	return total_keys, err
}
